CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    created_at VARCHAR(25) NOT NULL,
    sent BOOLEAN DEFAULT FALSE
) ENGINE = InnoDB;